### ISSUE TITLE
2018.12.27現在、README記載通りのビルド環境を用意できない

### ISSUE THREAD

**Issue by nkjzm** [sh-akira/VirtualMotionCapture#5]
# 状況

[ビルド手順](https://github.com/sh-akira/VirtualMotionCapture#%E3%83%93%E3%83%AB%E3%83%89%E6%89%8B%E9%A0%86)の内容にそってビルド環境を整えようとすると、FinalIKの1.7が現状入手困難であるため、再現ができない。

その他アセットのバージョンについては[こちらのﾌﾟﾙﾘｸ](https://github.com/sh-akira/VirtualMotionCapture/pull/4)を参照。

> Unity 5.3.6, 2017.3.1, and 2018.2.4 
https://assetstore.unity.com/packages/tools/animation/final-ik-14290

また、Final IK 1.8(2018.12.27現在の最新版)のサポート状況は上記の通り。手順に記載されている2018.1系ではコンパイルが通らないことを確認した。

# 考えられる対策
Unity2018.2.xとFinal IK 1.8を使用し、マイグレーションを行う。
Final IK 1.8ではいくつか変更があることに注意。(参考: https://twitter.com/nkjzm/status/1078203322501222400)

**Comment by sh-akira** [comment]
https://github.com/sh-akira/VirtualMotionCapture/commit/5fa25a33fdfa56e6355ca97d26faf9f3e7ed389c

**Comment by sh-akira** [comment]
全てのライブラリ類を最新に更新しました。ありがとうございました。
